version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: recipe-mysql
    restart: always
    environment:
      MYSQL_DATABASE: recipes
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"   # Only for local dev; remove in prod
    volumes:
      - mysqldata:/var/lib/mysql

  recipe-app:
    build: .
    container_name: recipe-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker-mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/recipes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysqldata:
